#!c:\users\asus\documents\pycharmprojects\modelagem-computacional\propagação em redes\propagacao_env\scripts\python.exe
"""Small script to execute the igraph command line interface"""
from igraph.app.shell import main
main()
